# Loader metadata
modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/eerussianguy/firmalife/issues"

# TFC
[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "Firmalife"
    credits = "EERussianguy, Charnuz, Dodo, Indi, Peffern, Lumintorious"
    authors = "EERussianguy, Charnuz, Dodo, Indi, Peffern, Lumintorious"
    description = '''A cooking and farming addon for TFC.'''

# Dependencies
[[dependencies.firmalife]]
    modId = "tfc"
    type = "required"
    versionRange = "${tfcVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.firmalife]]
    modId = "patchouli"
    type = "required"
    versionRange = "${patchouliVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.firmalife]]
    modId = "jei"
    type = "optional"
    versionRange = "${jeiVersionRange}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.firmalife]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.firmalife]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"

